### ISSUE TITLE
Compatibility with ItemHopper

### ISSUE THREAD

**Issue by safisynai** [war3i4i/ItemDrawers#3]
Thank you for continuing this mod, and already being so quick on compatibility fixes!

The old ItemDrawers mod worked with [Item Hopper](https://github.com/MSchmoecker/ValheimHopper) in that hoppers could insert and remove items from drawers - this isn't presently the case with your Item Drawers mod. If such compatibility is feasible, it would be nice to have :)

**Comment by war3i4i** [comment]
That's something that Item Hopper mod dev should consider adding to his mod

**Comment by safisynai** [comment]
I'm not sure if it had any specific compatibility code prior, I think it just incidentally worked due to the old Item Drawers still being regular containers (but I'm sure that approach must've had its own issues). I'll ping @MSchmoecker just so they're aware of this :)

**Comment by war3i4i** [comment]
Old ItemDrawers were using vanilla Container component which had no sense at all (since its only holding one item). It was overkill by perfomance downgrade and also made mod very problematic with many other mods.

I'm using different approach instead by writing my own "item-holder" component from scratch by just using string item and int value amount. ([DrawerComponent.cs](https://github.com/war3i4i/ItemDrawers/blob/master/DrawerComponent.cs))

That way my mod is basically "independent" from any vanilla components and also will not cause any issues whatsoever in future. Only downside of that ofc is that other mods that are using Container component (such as Craft from containers, Item Hopper) can't interact with my drawers

Its not a problem tho since i wrote an API ([API.cs](https://github.com/war3i4i/ItemDrawers/blob/master/API.cs)) that everyone can use

**Comment by war3i4i** [comment]
For example I've Forked Azu's Crafty Boxes mod (Craft from containers) and added mydrawers API into it so that it can use my component as container [Azu Crafty Boxes](https://github.com/war3i4i/AzuCraftyBoxes)

**Comment by MSchmoecker** [comment]
I'll consider adding support for interaction with ItemHopper, the API seems easy to use. Although with the current implementation it won't be possible, because the drawers interact with the player inventory directly on `WithdrawItem_Request` and `AddItem_Request`, disqualifing interactions from a piece.

The previous compatiblity with the old ItemDrawers was possible because it relied on the Container component where MultiUserChest could handle safe item addition and withdraw. Although a few patches to ItemDrawers were needed, to properly handle everything.
